using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Alice.Engine;

[Generator]
public class AliceGenerator : IIncrementalGenerator
{
    private const string AttributeFqn = "Alice.Attributes.AliceTableAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        /*
        // ШАГ 2: Синтаксический фильтр — дёшево, без семантики
        IncrementalValuesProvider<TypeDeclarationSyntax> syntaxProvider =
            context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateType(node),
                transform: static (ctx, _) => GetSemanticTarget(ctx)
            )
            .Where(static x => x is not null)!;

        // ШАГ 3: Комбинируем с компиляцией
        IncrementalValueProvider<(Compilation, ImmutableArray<TypeDeclarationSyntax>)> combined =
            context.CompilationProvider.Combine(syntaxProvider.Collect());

        // ШАГ 4: Регистрируем финальный шаг генерации
        context.RegisterSourceOutput(combined, static (ctx, source) =>
            Execute(ctx, source.Item1, source.Item2));*/
    }

    private static void Execute(
        SourceProductionContext ctx,
        Compilation compilation,
        ImmutableArray<TypeDeclarationSyntax> types)
    {
        if (types.IsDefaultOrEmpty) return;

        var attrSymbol = compilation.GetTypeByMetadataName(AttributeFqn);
        if (attrSymbol is null) return;

        foreach (var tds in types)
        {
            var model = compilation.GetSemanticModel(tds.SyntaxTree);
            if (model.GetDeclaredSymbol(tds) is not INamedTypeSymbol typeSymbol) continue;

            // Достаём атрибут через символьную модель
            var attrData = typeSymbol.GetAttributes()
                .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(
                    a.AttributeClass, attrSymbol));
            if (attrData is null) continue;

            string tableName = attrData.ConstructorArguments[0].Value?.ToString() ?? typeSymbol.Name;

            // Достаём поля: все публичные instance-свойства и поля
            var members = typeSymbol.GetMembers()
                .Where(m => m.DeclaredAccessibility == Accessibility.Public
                            && !m.IsStatic
                            && m is IPropertySymbol or IFieldSymbol);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine($"namespace {typeSymbol.ContainingNamespace.ToDisplayString()}");
            sb.AppendLine("{");
            sb.AppendLine($"    // Table: {tableName}");
            sb.AppendLine($"    public static class {typeSymbol.Name}SqlMeta");
            sb.AppendLine("    {");
            sb.AppendLine($"        public const string TableName = \"{tableName}\";");
            sb.AppendLine("        public static readonly Dictionary<string, string> Columns = new Dictionary<string, string>");
            sb.AppendLine("        {");

            foreach (var member in members)
            {
                string memberType = member switch
                {
                    IPropertySymbol p => p.Type.ToDisplayString(),
                    IFieldSymbol f => f.Type.ToDisplayString(),
                    _ => "unknown"
                };
                sb.AppendLine($"            {{ \"{member.Name}\", \"{memberType}\" }},");
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            ctx.AddSource($"{typeSymbol.Name}SqlMeta.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static TypeDeclarationSyntax? GetSemanticTarget(GeneratorSyntaxContext ctx)
    {
        var tds = (TypeDeclarationSyntax)ctx.Node;

        foreach (var attrList in tds.AttributeLists)
            foreach (var attr in attrList.Attributes)
                if (ctx.SemanticModel.GetSymbolInfo(attr).Symbol is IMethodSymbol methodSymbol)
                    if (methodSymbol.ContainingType.ToDisplayString() == AttributeFqn)
                        return tds;

        return null;
    }

    private static bool IsCandidateType(SyntaxNode node) => node is TypeDeclarationSyntax tds
               && tds is ClassDeclarationSyntax or StructDeclarationSyntax
               && tds.AttributeLists.Count > 0;
}
